title: Joel Jaison
logo: https://media.licdn.com/dms/image/C4D03AQEUkiSWXCNZqQ/profile-displayphoto-shrink_100_100/0/1660058714723?e=1720656000&v=beta&t=NyRr0pVmqpguw5sMSE4dije8BvjtWjXFVqMfOIQ7m3s
description: MERN stack devloper
show_downloads: true
theme: jekyll-theme-minimal
